---
title: "FAQ"
output: 
  github_document:
    html_preview: false
    toc: FALSE
---

Please refer to a <a href="https://youtu.be/3SKC-29AwME?t=252" target="_blank">recorded webinar</a> or the <a href="www/Growing Shade User Guide (January 2022).pdf" target="_blank">text user guide for help using the tool. Short answers to frequently asked questions can be found below. 
<br>

**Q. How are the priority layers created?**
<span style='line-height: .1;'><br></span>
A. Priority scores are calculated using equally-weighted variables.

**Q. How did you choose the variables for the priority layers?**
<span style='line-height: .1;'><br></span>
A. Presets are developed to provide starting points for various stakeholder groups. 

**Q. How can I isolate individual variables? Can I visualize the patterns for a single variable?**
<span style='line-height: .1;'><br></span>
A. Click on the "Custom" priority layer, then select a single variable. 

**Q. I'm interested in understanding how the tree canopy intersects with a specific racial or ethnic group rather than all communities of color.**
<span style='line-height: .1;'><br></span>
A. Raw data can be downloaded from within the "mapping tool" tab if you wish explore relationships not shown in the report.

**Q. Why do different canopy tools show different priority areas?**
<span style='line-height: .1;'><br></span>
A. There are several tools, like the <a href = "https://www.americanforests.org/our-work/tree-equity-score/" target = "_blank">American Forests’ Tree Equity Score</a>, that are worth exploring. The Growing Shade Project was created to specifically address the unique challenges and opportunities of our region, reflecting priorities that may not be so readily detailed in a national, more generalized tool. Growing Shade responds to the specific climate change, conservation, environmental justice, and public health issues in our region. Also, users can customize our tool to address their individualized needs, which can be highly specific (for instance, a user may want to focus on planting trees in areas to enhance health benefits in children).  

Growing Shade's priority scores range from 0 (lowest priority) to 10 (highest priority). Distance between priority scores can be interpreted on a continuous, linear scale. For instance, the difference between priority scores of 4 and 5 is the same as the difference between priority scores of 5 and 6 (both have a difference of 1). 

**Q. Why do different canopy tools show different canopy coverage percents? How did you decide on a goal of 45% tree canopy coverage?**
<span style='line-height: .1;'><br></span>
A. We created this tool to respond to the stakeholder need of providing up-to-date, actionable data. Therefore, we focus on satellite data to provide current data that can be used in decision-making. Current data is necessary to manage impacts from invasive species like emerald ash borer or respond to emerging climate hazards.

To get current (near real-time) data, Growing Shade leverages Sentinel-2 satellite data. While Sentinel-2 data has excellent temporal resolution, the spatial resolution is 10 meters squared. This is often a bigger area than the canopy from a single tree. When comparing tree canopy detected from Sentinel-2 data with a more spatially accurate (but less temporally accurate) <a href = "https://gisdata.mn.gov/dataset/base-landcover-twincities" target = "_blank">1 meter squared landcover data set</a>, there was high correlation but Sentinel-2 data detects about a quarter more tree canopy as the 1 meter squared landcover data. Essentially, this means that the methods in Growing Shade detect areas with at least 89% tree canopy coverage. We re-scaled our data using this relationship to improve the clarity of messaging. More information is given in the "methods" tab. 

There is <a href = "https://www.americanforests.org/blog/no-longer-recommend-40-percent-urban-tree-canopy-goal/" target = "_blank">not a universal optimal percentage of tree canopy cover</a> for goal setting. Within the 7-county metro area, it is estimated that the <a href = "https://files.dnr.state.mn.us/eco/mcbs/natural_vegetation_of_mn.pdf" target = "_blank">natural vegetation</a> had 30.5% of land area covered by forests and another 40.7% was covered by oak woodlands and brushlands. Tree cover in forests can be up to 100% while tree cover in oak woodlands can <a href="https://files.dnr.state.mn.us/assistance/nrplanning/community/mlccs/mlccs_manual_v5_4.pdf" target = "_blank">vary from 10-70% tree cover</a>. Thus, total tree cover across the 7-county region may have been as low as 34.6% (using an estimate of 10% tree cover in oak woodlands) or as high as 59.0% (using an estimate of 70% tree cover in oak woodlands). The average of these values is 46.8% which we have rounded to our goal of 45% tree canopy cover.  

**Q. Why doesn't the tool show trees where there are trees? Why does the tool show trees where there are not trees?**
<span style='line-height: .1;'><br></span>
A. Calibration revealed that the tree layer mapped in Growing Shade identifies areas which have at least 89% tree canopy cover. The tree canopy has been identified from satellite imagery using a machine learning method rather than collecting on-the-ground data. More information is given in the "methods" tab. 

**Q. Is it possible to get the type of information Growing Shade provides for other areas? Is it possible to get historic data about the tree canopy from Growing Shade?**
<span style='line-height: .1;'><br></span>
A. Right now the focus of Growing Shade is on current conditions within the 7-county Twin Cities metro. We do have future updates and new features of this tool planned, but cannot ensure that any updates will meet specific needs. Please look to the "resources" tab to see if another product might meet your needs, and thank you for your interest and understanding.

<br>
<br><br><br><br>


