---
title: "External resources"
output: 
  github_document:
    html_preview: false
    toc: false
# params: 
#   actor_id: "esch" 
#   data_date: "2020-03-26"
#   sha: "sha"
---

Growing Shade is a unique tool that highlights stories and allows users to create custom reports to inform tree canopy enhancement and preservation for the greater Twin Cities region. 

There are additional tools and resources that may be useful for this work.  Please consider the list below as a starting point. Additionally, when planning and prioritizing urban forestry work, tools and data cannot substitute for stakeholder engagement to understand community-specific concerns or opportunities. The on-the-ground knowledge of residents and the expertise of local practitioners are valuable sources of information.



- **Tools**
  - *What additional tools and assessments exist to help prioritize where to plant trees and maintain tree canopy?*
    - <a href = "https://www.itreetools.org/tools/which-tool-should-i-use" target = "_blank">iTree tools</a> to quantify the benefits and values of trees, including tools for individuals such as homeowners concerned with individual or small amounts of trees
    - <a href = "https://www.americanforests.org/our-work/tree-equity-score/" target = "_blank">American Forests Tree Equity Score project</a> 
    - <a href = "https://gis-hennepin.opendata.arcgis.com/pages/tree-planting" target = "_blank">Hennepin County, MN Tree Canopy Tree Planting Priority Areas</a>
    - <a href = "https://www.stpaul.gov/departments/parks-recreation/natural-resources/forestry/urban-tree-canopy-assessment" target = "_blank">City of Saint Paul Urban Tree Canopy Assessment 2011</a>
  - *Where can I lean more about the benefits provided by urban forests and learn how to build them?*
    - <a href = "https://www.vibrantcitieslab.com/" target = "_blank">Vibrant Cities Lab</a>
  - *Where can I learn more about the impact of emerald ash borer?*
    - <a href = "https://mnag.maps.arcgis.com/apps/webappviewer/index.html?id=63ebb977e2924d27b9ef0787ecedf6e9" target = "_blank">Minnesota Department of Agriculture's Emerald Ash Borer Map</a>
- **Planting Trees and Native Vegetation**
  - *What trees are predicted to do well in future climate conditions?*
    - <a href = "https://forestadaptation.org/sites/default/files/2021-03/TwinCitiesMN_TreeSpeciesVulnerability.pdf" target = "_blank">Climate Change Vulnerability of Urban Trees: Twin Cities, Minnesota</a>
  - *What the best way to plant a tree?*
    - <a href = "https://www.youtube.com/watch?v=yQ0Xo7cfMqs" target = "_blank">Tree Trust video</a>
  - *Where can I learn about native plants (trees, grasses, wildflowers): the benefits, purchasing and planting?*
    - <a href = "https://mnnps.org/links/" target = "_blank">Minnesota Native Plant Society</a>
    - <a href = "https://extension.umn.edu/find-plants/native-plants" target = "_blank">University of Minnesota Extension</a>
- **Climate Change** 
  - *Where can I find more information about climate change impacts in the Twin Cities?*
    - <a href = "https://www.fs.usda.gov/sites/default/files/fs_media/fs_document/urbannatureforhumanhealthandwellbeing_508_01_30_18.pdf%22 %EF%BF%BDHYPERLINK %22https://metrocouncil.org/Communities/Planning/Local-Planning-Assistance/CVA.aspx"                 target = "_blank">Climate Vulnerability Assessment by Metropolitan Council for the Twin Cities</a>
    - <a href = "https://metrocouncil.maps.arcgis.com/apps/webappviewer/index.html?id=fd0956de60c547ea9dea736f35b3b57e"
            target = "_blank">Extreme Heat Map Tool </a> by Metropolitan Council
    - <a href = "https://metrocouncil.maps.arcgis.com/apps/MapJournal/index.html?appid=7d9cdd3929e9439bb5b25aa1186d5783"
            target = "_blank">Extreme Heat Story Map </a> by Metropolitan Council
- **Human Health**
  - *Where can I learn about the impacts of tree on human health?*
    - <a href = "https://www.fs.usda.gov/sites/default/files/fs_media/fs_document/urbannatureforhumanhealthandwellbeing_508_01_30_18.pdf" target = "_blank">US Forest Service Report: Urban Nature for Human Health and Well-being 2018</a>
- **Connect and Learn**
  - *Where can I connect with others working to grow our tree canopy in the Twin Cities or across Minnesota?*
    - <a href = "https://www.mnstac.org/" target = "_blank">Minnesota Shade Tree Advisory Committee</a>
    - <a href = "https://trees.umn.edu/minnesota-shade-tree-short-course" target = "_blank">Minnesota Shade Tree Short Course</a>
  - *How can my city receive recognition or a certification for our urban forestry work?*
    - <a href = "https://www.arborday.org/programs/treeCityUSA/index.cfm" target = "_blank">Tree City USA</a>
    - <a href = "https://greenstep.pca.state.mn.us/bp-detail/81726" target = "_blank">GreenStep Cities program</a>
- **What’s Next** 
  - *What new projects are underway that could support and inform urban forests in the Twin Cities?*
    - <a href = "https://mspurbanlter.umn.edu/overview" target = "_blank">Urban LTER (Long-term Ecological Research) in the Twin Cities</a>
    
<br><br><br><br><br>



