---
output: 
  github_document:
    html_preview: false
# params: 
#   actor_id: "esch" 
#   data_date: "2020-03-26"
#   sha: "sha"
---


## What next?

<br>
Most importantly, this was a quick(ish) test to see if I could pull things together! IF any of this seems useful, it needs some collaboration! **Check back closer to the technical meeting on June 28 in order to see some progress (hopefully!) towards some of these items. It will be more conceptual, to provide a jumping off point for discussions we might wish to have. Thanks again for your patience.**

<br>
Further, I am thinking that it could be cool to entertain these ideas:

- Resources...
  - what about links to $ or technical assistance? 
- Scenario planning....
  - maybe if we know something about the species, we can do a "back of the envelope" forecast of carbon stock and/or carbon sequestration rate in 5, 10, 20 years?
  - similarly, we might be able to estimate something about energy costs if we know the tree species (probably a function of the height of tree and residence, distance from tree to residence, tree growth rate, current energy costs)
- Planting and selecting species for climate resilience/adaptation...
  - can we incorporate info about existing species diversity to ensure that future tree plantings have species diversity
  - we could do an interactive tree selection tool. ask questions like: do you care about height (trees that grow > 80 ft? Or what about < 40 ft?). what about growth rate and longevity? disease resistance? water needs? tolerance to air/soil pollution or VOC emissions? fruit producing?
- Add your story...
  - I made a cool interactive of reasons people love our regional parks (so heartwarming!)... it might be fun to solicit letters for this project and add a whole bunch of humanity and people-connections to this project?
- Is it important to see how the region has changed over time?
  - 10 x 10 meter NDVI started in 2017 (for this application, the 30 x 30 meter landsat data doesn't seem ideal even though it goes back for 40 years). If we get summer 2021 data in here (we'd have to wait until the end of August, probably), then we could show 5 years of change in the region? i cant really think of a reason that would add something to the project, but maybe others have strong feelings/new ideas?!
- State-wide tool...
  - using NDVI makes it easy to scale this tool to any geography. To scale across the entire state, we're probably gonna need a javascript whiz/apprentice...and it actually might be faster to build it on google earth engine (it's open source and SUPER cool!) vs RShiny (because google has bigger servers for storing data than we do...). if we scale this tool in some capacity using NDVI, i'd like to think about reaching out to the google earth engine people because they seem keen to build capacity in this space. I think using census data like i've done here makes this tree planting tool way cooler than what google has piloted for planting trees in the city of LA.). https://insights.sustainability.google/labs/treecanopy
  - also census data is nice to use because that also scales to any geography. we need matt s's brain for that! matt's brain would also be ideal if we'd like to map census block groups rather than census tracts
- do we like using NDVI?  
  - i'm pretty evangelical about ndvi, but it does have shortcomings. 
  - what should we use as a cutoff threshold for designating areas which would be good candidates for tree planting? I used areas below 0.5 NDVI. We see known greenspace being not designated as priority tree planting areas (check on the Minneapolis Central Library greenroof, any woods, etc.). Very green and grassy areas **do not** show up as priority areas for planting trees (check out baseball fields or golf courses, in order to change this, we could alter the NDVI threshold (try 0.7?) or incorporate lidar data. Lidar data is currently quite old for our region (but maybe being updated???). I also don't know how to process lidar data). i do know that flying lidar is SUPER expensive, so if we rely too heavily on lidar we might not be able to scale the tool without significant data costs. 
  - i favor using NDVI as a measure of designating priority areas for planting trees because it is super up-to-date (real time measurements, HOLY COW) and has impressive spatial resolution (10 x 10 meters - WOW) and exists for everywhere in the world (scale this tool for ANYWHERE). 
  - The detailed 1x1m map of twin cities land cover is beautiful, but at least 5 years out of date and only exist for the 7county metro region. so the utility seems diminished if we wish to truly have a dynamic tool which could be scaled to state-wide levels without too much problem

<br>
<br>
