---
output: 
  github_document:
    html_preview: false
# params: 
#   actor_id: "esch" 
#   data_date: "2020-03-26"
#   sha: "sha"
---


<!-- # Where to plant trees? -->

<!-- <br> -->

There are many dimensions that can and should be considered when deciding where to plant trees.
<br>

- **Existing tree cover**: knowing which areas have relatively low tree cover versus areas that have relatively high tree cover can help direct tree planting efforts.
- **Equity**: communities of color and other marginalized groups disproportionately live in areas which lack tree cover and/or have high negative externalities which could be mitigated in part by tree cover (air pollution, etc.)
- **Existing land use**: information about land use can help direct messaging and outreach (ie if opportunities exist for planting trees within residential area, the messaging will look very different than if the greatest opportunities for planting trees lies within commercial zoned areas)
- Other: …

<!-- <br> -->
<!-- Similarly, there are multiple things to consider in making a useful tool: -->
<!-- - **Understandable**: clear and actionable conclusions need to be drawn from complex and disparate data sources. Conclusions should be understandable to the general public (given that tree planting fundamentally impacts people and neighborhoods), to practitioners (to make informed decisions about planting trees), and to subject matter experts (to facilitate the iterative nature of this work and ensure the tool incorporates the best available research). -->
<!-- - **Narrative**: planting trees today will change the trajectory of a neighborhood's canopy for the future. Incorporating stories needs to be part of the tool... -->
<!-- - **Research-based**: this tool should incorporate relevant research and be transparent in our methods. This tool should be designed flexibly so that new research and new data sources can improve the conclusions (especially around climate resiliency/adaptation), spatial accuracy (down to 1m in accuracy would be the gold standard), and geographic spread (expanding from the Twin Cities region to statewide and beyond) of this tool. -->
<!-- - **Interactive**: knowing that different funding programs and/or local priorities will dictate on-the-ground action (of planting trees), this tool should allow for users to set their own prioritization scheme if they so desire. -->
 
<br> This tool aggregates data to help facilitate discussions around enhancing our region’s tree canopy in order to improve climate resilience, livability, economic opportunity, and beauty. See the Methods tab for more information. 

<br> **Note, the detailed 'priority areas' does take a while to load, because there are a lot of areas without trees. Mapping 'NOT priority areas', or areas with existing trees, would be faster but potentially less useful. We can absolutely map different geographies below (think city boundaries rather than tract boundaries for instance), allow for users to download customized reports, and/or allow users to "weight" the priority variables differently (ie select different numbers of variables across categories, but weight each category equally). We'd just need to think what would be truly useful rather than distracting.**

<!-- Select variables of interest at the left and update map to view results. Warm and bright (yellow, orange) values and high ranks correspond to ‘opportunity zones’ where new tree plantings could have disproportionately positive impacts (values closer to 10). Cool and dark colors (black, purple) correspond to lower opportunity areas (values closer to zero). Click on any tract to get more information. -->

<!-- <br> -->
<!-- There is the capability to plot the human dimensions at the Census block group level (finer resolution than tracts, which are shown here). The data pieces are not yet aggregated in that way, however. As this is just a proof-of-concept idea, so I figured it didn't matter. All the data pieces are weighted equally, but we could weight them differently too. This is just my take on this and would need much more work/input/etc. if we wish to continue down this avenue..... -->

<br>

<!-- ### Methods -->
<!-- Pulling together: -->
<!-- - "Greenness" (normalized difference vegetation index (NDVI) from Sentinel-2, peak NDVI in 2020 aggregated to the block group level and also at 10x10m resolution) -->
<!-- - Equity considerations data -->
<!-- - Existing land use -->
