# all package calls

requireNamespace("readxl", quietly = TRUE)
requireNamespace("fs", quietly = TRUE)
requireNamespace("janitor", quietly = TRUE)
requireNamespace("tidyverse", quietly = TRUE)

library(sf)
library(tidyverse)
library(tigris)
library(golem)
library(leaflet)
library(RSocrata)
library(fs)
library(janitor)
library(raster)
library(terra)
library(readxl)
library(factoextra)
library(corrplot)
library(Hmisc)
library(cowplot)
library(dplyr)
