---
output: 
  github_document:
    html_preview: false
# params: 
#   actor_id: "esch" 
#   data_date: "2020-03-26"
#   sha: "sha"
---

#### Variation in geographies

We provide two ways of looking at the distribution of values. 

<br>
On the top is a density plot. The more geographic areas there are at a particular value, the taller this plot gets. Where this plot is taller at the right hand side, most geographic areas have low values of the characteristic. Where this plot is wider at the left hand side, most geographic areas have high values of the characteristic. 

<br>
On the bottom is a box plot, where each grey circle represents one geographic area. When the grey circles are more spread out, there is more variation across geographic areas. The line in the middle of the box shows the median value: half of the geographic areas fall below the median, and half of them lie above the median. The median is also known as the 50th percentile. The top and bottom edges of the box show the 75th percentile (the value below which 75% of the geographic areas fall) and the 25th percentile (the value below which 25% of the geographic areas fall). Geographic areas located above and below the vertical lines extending from the box are particularly extreme values.
